# Generated by Django 2.2.2 on 2019-06-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_word_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='examples',
            field=models.CharField(default='Examples', max_length=1000),
        ),
    ]
