# Generated by Django 2.2.2 on 2019-06-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190604_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='city',
            field=models.CharField(default='Moscow', max_length=100),
        ),
        migrations.AddField(
            model_name='word',
            name='date',
            field=models.CharField(default='0-0-0-0.0.0', max_length=100),
        ),
        migrations.AddField(
            model_name='word',
            name='updater',
            field=models.CharField(default='anonym', max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.TextField(blank=True, default='Definition', null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='examples',
            field=models.TextField(blank=True, default='Examples', null=True),
        ),
    ]
