# Generated by Django 2.2.11 on 2020-03-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20190605_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.CharField(default='2020-03-31-13.12.40', max_length=100),
        ),
    ]
