# Generated by Django 2.2.11 on 2020-03-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200331_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.CharField(default='2020-03-31-13.26.53', max_length=100),
        ),
    ]
