# Generated by Django 2.2.11 on 2020-04-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200416_1254'),
        ('pages', '0012_auto_20200331_1451'),
    ]

    operations = [
    ]
