# Generated by Django 2.2.11 on 2020-04-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20200416_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.CharField(default='2020-04-17-14.09.37', max_length=100),
        ),
    ]
