# Generated by Django 2.0.7 on 2019-06-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Word',
        ),
    ]
