# Generated by Django 2.2.2 on 2019-06-04 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_word_examples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='examples',
        ),
    ]
