# Generated by Django 2.2.2 on 2019-06-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_word_examples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='description',
        ),
        migrations.AddField(
            model_name='word',
            name='definition',
            field=models.TextField(blank=True, default='Description', null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='examples',
            field=models.TextField(blank=True, default='Examples', null=True),
        ),
    ]
