# Generated by Django 2.2.11 on 2020-03-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0010_auto_20200331_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.CharField(default='2020-03-31-13.14.14', max_length=100),
        ),
    ]
