# Generated by Django 2.2.11 on 2020-03-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0013_auto_20200331_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.CharField(default='2020-03-31-14.51.39', max_length=100),
        ),
    ]
