# Generated by Django 2.2.11 on 2020-04-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0014_auto_20200331_1451'),
        ('words', '0010_auto_20200416_1254'),
    ]

    operations = [
    ]
