# Generated by Django 2.2.11 on 2020-04-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0016_auto_20200416_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='word',
            name='likes',
        ),
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.CharField(default='2020-04-16-21.04.16', max_length=100),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.ForeignKey(on_delete='CASCADE', to='words.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislikes', models.ForeignKey(on_delete='CASCADE', to='words.Word')),
            ],
        ),
    ]
