# Generated by Django 2.2.11 on 2020-04-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0017_auto_20200416_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='word',
        ),
        migrations.AddField(
            model_name='word',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.CharField(default='2020-04-16-21.09.30', max_length=100),
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
